### ISSUE TITLE
 Directory 'static/' does not exist

### ISSUE THREAD

**Issue by CaptainChristmas** [lxulxu/pdf-to-markdown#5]
python start.py --file sbce-cn5-364p-1_nj_nx.pdf
Traceback (most recent call last):
...
  File "D:\ANACONDA\envs\pdftomarkdown\lib\site-packages\fitz\__init__.py", line 1, in <module>
    from frontend import *
  File "D:\ANACONDA\envs\pdftomarkdown\lib\site-packages\frontend\__init__.py", line 1, in <module>
    from .events import *
  File "D:\ANACONDA\envs\pdftomarkdown\lib\site-packages\frontend\events\__init__.py", line 1, in <module>
    from .clipboard import *
  File "D:\ANACONDA\envs\pdftomarkdown\lib\site-packages\frontend\events\clipboard.py", line 2, in <module>
    from ..dom import Event
  File "D:\ANACONDA\envs\pdftomarkdown\lib\site-packages\frontend\dom.py", line 439, in <module>
    from . import dispatcher
  File "D:\ANACONDA\envs\pdftomarkdown\lib\site-packages\frontend\dispatcher.py", line 15, in <module>
    from . import config, server
  File "D:\ANACONDA\envs\pdftomarkdown\lib\site-packages\frontend\server.py", line 24, in <module>
    app.mount(config.STATIC_ROUTE, StaticFiles(directory=config.STATIC_DIRECTORY), name=config.STATIC_NAME)
  File "D:\ANACONDA\envs\pdftomarkdown\lib\site-packages\starlette\staticfiles.py", line 60, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'static/' does not exist
这个是什么问题呀大佬

**Comment by lxulxu** [comment]
参考
https://stackoverflow.com/questions/67982760/raise-runtimeerrorfdirectory-directory-does-not-exist-runtimeerror-dire
https://github.com/pymupdf/PyMuPDF/issues/523
看是否能解决，先pip uninstall fitz，再pip install PyMuPDF。
